--------------------------------------------------------
--  DDL for View VW_I_AIM_DISTRIBUTION_ADMS
--------------------------------------------------------

 -- CREATE OR REPLACE FORCE EDITIONABLE VIEW "WATERINF"."VW_I_AIM_DISTRIBUTION_ADMS" ("ICS_ASSET_ID", "COMMS_BURST_FIT_TUNED", "COMMS_LENGTH_CUST", "COMMS_LENGTH_TWUL", "DMA_DET_HRS_AVG", "DMA_ESPB_AVG", "DMA_LEAKAGE_LOWEST", "MAINS_BURST_FIT_TUNED", "MAINS_COMMS_COUNT", "MAINS_COMMS_COUNT_L", "MAINS_COMMS_COUNT_M", "MAINS_COMMS_COUNT_S", "MAINS_CORR_FE", "MAINS_DG2", "MAINS_DIAM", "MAINS_DIAM_BIN", "MAINS_DMA", "MAINS_FAMILY_TYPE", "MAINS_INSTALL", "MAINS_ITS", "MAINS_ITS_MEAN", "MAINS_ITS_0_3", "MAINS_ITS_3_6", "MAINS_ITS_0_4", "MAINS_ITS_4_6", "MAINS_ITS_6_12", "MAINS_ITS_12_24", "MAINS_ITS_24_48", "MAINS_ITS_2_7", "MAINS_ITS_7", "MAINS_LENGTH", "MAINS_MATERIAL_BIN", "MAINS_MATERIAL_GROUP", "MAINS_MJR_ROAD", "MAINS_MNR_ROAD", "MAINS_MOTORWAY", "MAINS_RAIL", "MAINS_SURFACE_TYPE", "MAINS_WRZ", "AMBULANCESTATION", "AQUEDUCT", "BASEMENT", "COMMERCIAL", "EDUCATION", "FIRESTATION", "GOVERNMENT", "HOSPITAL", "INLANDWATER", "LISTEDBUILDING", "ELECTRICITYSUBSTATION", "TUNNELENTRANCE", "MOTORWAYAROAD", "SUBWAY", "POLICESTATION", "RAILWAYHIGHSPEED", "RAILWAY", "RAMSAR", "REDROUTE", "RESERVOIRSERVICEEMBANKMENT", "RESERVOIRSERVICEFLOOD", "RESERVOIRSTATUTORYEMBANKMENT", "RESERVOIRSTATUTORYFLOOD", "RESERVOIRSTORAGEEMBANKMENT", "RESERVOIRSTORAGEFLOOD", "RESIDENTIALPROPERTY", "SCHEDULEDMONUMENT", "SSSI", "UNDERGROUNDSTATION", "WORLDHERITAGESITE") AS 
  Select 
    core.ICS_ASSET_ID,
--BOROUGH_SCALAR   -not required
  --COMMS_BURST_COUNT,
  Comms_Model.COMMS_BURST_FIT_TUNED COMMS_BURST_FIT_TUNED,
--COMMS_CS_LEAKAGE_RES
--COMMS_LEAKAGE_CSL_FIT  --No Process
--COMMS_LEAKAGE_TW_FIT  --No PRocess
  Comms.COMMS_CS_LEN COMMS_LENGTH_CUST,
  Comms.COMMS_TW_LEN COMMS_LENGTH_TWUL,
--COMMS_TW_LEAKAGE_RES
--DMA_AVG_COMMS
--DMA_AVG_COMMS_SIZE
--DMA_AVG_INSTALL
  DMADETHRS.AVGDETHRS_4YRS DMA_DET_HRS_AVG,
 DMAESPB.AVG_ESPB DMA_ESPB_AVG,
--DMA_LEAKAGE_AVG
  min_leak.LOW_LEAK_MEDIAN_16 DMA_LEAKAGE_LOWEST,
--DMA_METERING_FLAG  --not required
--MAINS_BOROUGHS
--MAINS_BURST_COUNT
  Burst_model.FIT_TUNED MAINS_BURST_FIT_TUNED,
  (Comms.COMMS_SMALLDIA_COUNT+Comms.COMMS_MEDIUMDIA_Count+Comms.COMMS_LARGEDIA_COUNT) MAINS_COMMS_COUNT,
  Comms.COMMS_LARGEDIA_COUNT MAINS_COMMS_COUNT_L,
  Comms.COMMS_MEDIUMDIA_Count MAINS_COMMS_COUNT_M,
  Comms.COMMS_SMALLDIA_COUNT MAINS_COMMS_COUNT_S,
  dirt.SOIL_CORROSIVITY MAINS_CORR_FE,
--MAINS_COST_ZONE
  case  
    when VIZ_AIM.PROP_COUNT_LOW_PRESSURE is not null then VIZ_AIM.PROP_COUNT_LOW_PRESSURE --Previous AIM data
    when VIZ_MOD.PROP_COUNT_LOW_PRESSURE is not null then VIZ_MOD.PROP_COUNT_LOW_PRESSURE --VCM model
    else 0  
  end as   MAINS_DG2,
  core.DIAM MAINS_DIAM,
  core.DIAM_BIN MAINS_DIAM_BIN,
  core.DMA MAINS_DMA,
  (Select ADMS_STRING_VALUE from ADMS_CONFIG.T_I_LKP_CATEGORICAL where schema_name = 'WATERINF' and table_name = 'T_I_MAINS_TWUL' and FIELD_NAME_1 = 'HYDRAULICFAMILYTYPE' and SOURCE_VALUE_1 = MNTW.HYDRAULICFAMILYTYPE) MAINS_FAMILY_TYPE,
  core.DATE_INSTALL MAINS_INSTALL,
  case  
    when VIZ_AIM.PROP_COUNT_ISOLATED is not null then VIZ_AIM.PROP_COUNT_ISOLATED --Previous AIM data
    when VIZ_MOD.PROP_COUNT_ISOLATED is not null then VIZ_MOD.PROP_COUNT_ISOLATED --VCM model
    else 0 
  end as MAINS_ITS,
  itsdur.DURATION_MEAN MAINS_ITS_MEAN, 
  itsdur.DURATION_0_3_HRS MAINS_ITS_0_3, 
  itsdur.DURATION_3_6_HRS MAINS_ITS_3_6, 
  itsdur.DURATION_0_4_HRS MAINS_ITS_0_4, 
  itsdur.DURATION_4_6_HRS MAINS_ITS_4_6, 
  itsdur.DURATION_6_12_HRS MAINS_ITS_6_12, 
  itsdur.DURATION_12_24_HRS MAINS_ITS_12_24, 
  itsdur.DURATION_24_48_HRS MAINS_ITS_24_48, 
  itsdur.DURATION_2_7_DAYS MAINS_ITS_2_7, 
  itsdur.DURATION_OVER_7_DAYS MAINS_ITS_7, 
--MAINS_LEAKAGE_FIT
--MAINS_LEAKAGE_RES
  core.ASSET_LENGTH MAINS_LENGTH,
  core.ASSET_MATERIAL MAINS_MATERIAL_BIN,
  (Select ADMS_STRING_VALUE FROM ADMS_CONFIG.T_I_LKP_CATEGORICAL where schema_name = 'WATERINF' and TABLE_NAME = 'VW_I_AIM_TRUNK' and FIELD_NAME_1 = 'MATERIAL' and SOURCE_VALUE_1 = core.ASSET_MATERIAL) MAINS_MATERIAL_GROUP,
  (lens.AROAD+lens.BROAD) MAINS_MJR_ROAD,
  (lens.MINORROAD+lens.PATH+lens.ROADSIDE) MAINS_MNR_ROAD,
  lens.MOTORWAY MAINS_MOTORWAY,
--MAINS_PIPE_DENSITY
--MAINS_PRESSURE
--MAINS_PRESSURE_BIN
--MAINS_PROPERTIES
--MAINS_PROP_DENSITY
  lens.RAIL MAINS_RAIL,
  (Select name from T_I_PRODUCTION_OPS_AREA where core.ICS_REGION_ID = ICS_PROUCTION_OP_AREA_ID) MAINS_REGION,

--MAINS_REGION_OPS
--MAINS_RENOVATION
--MAINS_ROAD_DETAIL
  case when salt.ICS_SALINE_INTRUSION_ID is null THEN 'N' ELSE 'Y' END AS MAINS_SALINE,
  dirt.SOIL_SHRINK_SWELL MAINS_SHRINK_SWELL,
  (select ADMS_STRING_VALUE from ADMS_CONFIG.T_I_LKP_CATEGORICAL where TABLE_NAME = 'T_I_MODEL_TRUNK_POF' and FIELD_NAME_1 = 'SURFACE' and SOURCE_VALUE_1 =    
  DECODE ( GREATEST( NVL(lens.AROAD,0), 
              NVL(lens.MOTORWAY,0), 
              NVL(lens.MINORROAD,0), 
              NVL(lens.BUILDING,0), 
              NVL(lens.UNKNOWN,0), 
              NVL(lens.WATER,0), 
              NVL(lens.RAIL,0), 
              NVL(lens.BROAD,0), 
              NVL(lens.LAND,0), 
             NVL(lens.ROADSIDE,0), 
             NVL(lens.PATH,0)), 
             lens.AROAD , 'AROAD', 
              lens.MOTORWAY , 'MOTORWAY', 
              lens.MINORROAD, 'MINORROAD', 
              lens.BUILDING, 'BUILDING', 
              lens.UNKNOWN, 'UNKNOWN', 
              lens.WATER , 'WATER', 
              lens.RAIL, 'RAIL', 
              lens.BROAD, 'BROAD', 
              lens.LAND , 'LAND', 
              lens.ROADSIDE , 'ROADSIDE', 
              lens.PATH, 'PATH', 
                'UNKN') ) MAINS_SURFACE_TYPE, 
--MAINS_UNDERGROUND
  core.WRZ MAINS_WRZ,
--SS_AVERAGE_INSTALL
--SS_ID1
--SS_LENGTH

 case when FLD_2D.ICS_ASSET_ID is not null then FLD_2D.AMBULANCE else FLD_1D.AMBULANCE end as AmbulanceStation,
 
  case when FLD_2D.ICS_ASSET_ID is not null then FLD_2D.AQUADUCT else FLD_1D.AQUADUCT end as AQUEDUCT, 
  case when FLD_2D.ICS_ASSET_ID is not null then FLD_2D.BASEMENT else FLD_1D.BASEMENT end as BASEMENT, 
  case when FLD_2D.ICS_ASSET_ID is not null then FLD_2D.COMMERCIAL else FLD_1D.COMMERCIAL end as COMMERCIAL, 
  case when FLD_2D.ICS_ASSET_ID is not null then FLD_2D.EDUCATION else FLD_1D.EDUCATION end as EDUCATION, 
  case when FLD_2D.ICS_ASSET_ID is not null then FLD_2D.FIRE_STATION else FLD_1D.FIRE_STATION end as FIRESTATION, 
  case when FLD_2D.ICS_ASSET_ID is not null then FLD_2D.GOVERNMENT else FLD_1D.GOVERNMENT end as GOVERNMENT, 
  case when FLD_2D.ICS_ASSET_ID is not null then FLD_2D.HOSPITAL else FLD_1D.HOSPITAL end as HOSPITAL, 
  case when FLD_2D.ICS_ASSET_ID is not null then FLD_2D.WATERBODY else FLD_1D.WATERBODY end as InlandWater,  
 
  case when FLD_2D.ICS_ASSET_ID is not null then FLD_2D.LISTED_BUILDING else FLD_1D.LISTED_BUILDING end as LISTEDBUILDING,
 
  case when FLD_2D.ICS_ASSET_ID is not null then FLD_2D.ELECTRICITY else FLD_1D.ELECTRICITY end as ElectricitySubStation,
  case when FLD_2D.ICS_ASSET_ID is not null then FLD_2D.MAJOR_TUNNEL else FLD_1D.MAJOR_TUNNEL end as TunnelEntrance,
  case when FLD_2D.ICS_ASSET_ID is not null then FLD_2D.MOTORWAY_AROAD else FLD_1D.MOTORWAY_AROAD end as MotorwayARoad,
  case when FLD_2D.ICS_ASSET_ID is not null then FLD_2D.SUBWAY else FLD_1D.SUBWAY end as SUBWAY,
  case when FLD_2D.ICS_ASSET_ID is not null then FLD_2D.POLICE else FLD_1D.POLICE end as PoliceStation,
  case when FLD_2D.ICS_ASSET_ID is not null then FLD_2D.HIGH_SPEED_RAIL else FLD_1D.HIGH_SPEED_RAIL end as RailwayHighSpeed,
  case when FLD_2D.ICS_ASSET_ID is not null then FLD_2D.RAILWAY_LINE else FLD_1D.RAILWAY_LINE end as Railway,
  case when FLD_2D.ICS_ASSET_ID is not null then FLD_2D.RAMSAR else FLD_1D.RAMSAR end as RAMSAR,
  case when FLD_2D.ICS_ASSET_ID is not null then FLD_2D.RedRoute else FLD_1D.RedRoute end as RedRoute,
  PROX.E_SERVICE_RESERVOIR RESERVOIRSERVICEEMBANKMENT, 
  case when FLD_2D.ICS_ASSET_ID is not null then FLD_2D.SERVICE_RESERVOIR else FLD_1D.SERVICE_RESERVOIR end as ReservoirServiceFlood,
  PROX.E_STORAGE_RESERVOIR_STATUTORY RESERVOIRSTATUTORYEMBANKMENT, 
  case when FLD_2D.ICS_ASSET_ID is not null then FLD_2D.STORAGE_RESERVOIR_STATUTORY else FLD_1D.STORAGE_RESERVOIR_STATUTORY end as ReservoirStatutoryFlood,
  PROX.E_STORAGE_RESERVOIR RESERVOIRSTORAGEEMBANKMENT, 
  case when FLD_2D.ICS_ASSET_ID is not null then FLD_2D.STORAGE_RESERVOIR else FLD_1D.STORAGE_RESERVOIR end as ReservoirStorageFlood,
  case when FLD_2D.ICS_ASSET_ID is not null then FLD_2D.RESIDENTIAL else FLD_1D.RESIDENTIAL end as ResidentialProperty,
  case when FLD_2D.ICS_ASSET_ID is not null then FLD_2D.SCHEDULED_MONUMENT else FLD_1D.SCHEDULED_MONUMENT end as ScheduledMonument,
  case when FLD_2D.ICS_ASSET_ID is not null then FLD_2D.SSSI else FLD_1D.SSSI end as SSSI,
  case when FLD_2D.ICS_ASSET_ID is not null then FLD_2D.UNDERGROUND_STATION else FLD_1D.UNDERGROUND_STATION end as UndergroundStation,
  case when FLD_2D.ICS_ASSET_ID is not null then FLD_2D.WORLD_HERITAGE_SITE else FLD_1D.WORLD_HERITAGE_SITE end as WorldHeritageSite

from VW_I_ASSET_CORE core
left join T_PRED_MODEL_COMMS_RESULTS Comms_Model    on core.ICS_ASSET_ID = Comms_Model.ICS_ASSET_ID
left join T_PRED_MODEL_BURSTS_RESULTS Burst_model   on core.ICS_ASSET_ID = Burst_model.ICS_ASSET_ID
left join T_P_COMMS Comms                           on core.ICS_ASSET_ID = Comms.ICS_MAINS_ASSET_ID
left join T_P_SOILS dirt                            on core.ICS_ASSET_ID = dirt.ICS_ASSET_ID
left join T_P_SURFACELENGTHS lens                   on core.ICS_ASSET_ID = lens.ICS_ASSET_ID
left join T_I_MODEL_ITS_DURATION itsdur             on core.ICS_ASSET_ID = itsdur.ICS_ASSET_ID  
left join T_I_MAINS_TWUL MNTW                       on core.ICS_ASSET_ID = MNTW.ICS_ASSET_ID 
left join VW_P_AIM_HISTORIC VIZ_AIM                 on CORE.ICS_ASSET_ID = VIZ_AIM.ICS_ASSET_ID 
left join VW_P_VIZ_HISTORIC_MODELLED VIZ_MOD        on CORE.ICS_ASSET_ID = VIZ_MOD.ICS_ASSET_ID 
LEFT JOIN T_P_DMA_AVG_DET_HRS DMADETHRS             ON core.CLIENT_UID = DMADETHRS.DMA 
LEFT JOIN T_P_DMA_ESPB_AVG DMAESPB                  ON CORE.CLIENT_UID = DMAESPB.DMA 
left join T_P_SALINE_INTRUSION salt                 on core.ICS_ASSET_ID = salt.ICS_ASSET_ID
left join (SELECT fq2d.ICS_ASSET_ID,
  max(WATERBODY) WATERBODY,
  max(ELECTRIC_CABLE) ELECTRIC_CABLE,
  max(GAS_PIPE) GAS_PIPE,
  max(HIGH_SPEED_RAIL) HIGH_SPEED_RAIL,
  max(LISTED_BUILDING)LISTED_BUILDING,
  max(LOCAL_NATURE_RESERVE) LOCAL_NATURE_RESERVE,
  max(MAJOR_ROAD_JUNCTION) MAJOR_ROAD_JUNCTION,
  max(MAJOR_TUNNEL) MAJOR_TUNNEL,
  max(NATIONAL_NATURE_RESERVE) NATIONAL_NATURE_RESERVE,
  max(OIL_FUEL_DEPOT) OIL_FUEL_DEPOT,
  max(RAIL) RAIL,
  max(RAILWAY_LINE) RAILWAY_LINE ,
  max(RAILWAY_STATION) RAILWAY_STATION,
  max(RAMSAR) RAMSAR,
  max(RHPG) RHPG,
  max(SCHEDULED_MONUMENT) SCHEDULED_MONUMENT,
  max(SENSITIVE_BUILDING) SENSITIVE_BUILDING,
  max(SERVICE_RESERVOIR) SERVICE_RESERVOIR,
  max(SPECIAL_CONSERVATION_AREA) SPECIAL_CONSERVATION_AREA,
  max(SPECIAL_PROTECTED_AREA) SPECIAL_PROTECTED_AREA,
  max(SSSI) SSSI,
  max(STORAGE_RESERVOIR) STORAGE_RESERVOIR,
  max(SUBWAY) SUBWAY,
  max(UNDERGROUND_STATION) UNDERGROUND_STATION,
  max(WORLD_HERITAGE_SITE) WORLD_HERITAGE_SITE,
  max(ELECTRICITY) ELECTRICITY,
  max(GRAVEYARD) GRAVEYARD,
  max(RESIDENTIAL) RESIDENTIAL,
  max(GOVERNMENT) GOVERNMENT,
  max(FIRE_STATION) FIRE_STATION,
  max(EDUCATION) EDUCATION,
  max(COMMERCIAL) COMMERCIAL,
  max(AMBULANCE) AMBULANCE,
  max(POLICE) POLICE,
  max(HOSPITAL) HOSPITAL,
  max(AQUADUCT) AQUADUCT,
  max(BASEMENT) BASEMENT,
  max(MOTORWAY_AROAD) MOTORWAY_AROAD,
  max(STORAGE_RESERVOIR_STATUTORY) STORAGE_RESERVOIR_STATUTORY,
  max(REDROUTE) REDROUTE
FROM T_P_FLOOD_CONSEQUENCE fq2d
GROUP BY ICS_ASSET_ID
) FLD_2D              on core.ICS_ASSET_ID = FLD_2D.ICS_ASSET_ID 

left join (SELECT ICS_ASSET_ID,
  max(WATERBODY) WATERBODY,
  max(ELECTRIC_CABLE) ELECTRIC_CABLE,
  max(GAS_PIPE) GAS_PIPE,
  max(HIGH_SPEED_RAIL) HIGH_SPEED_RAIL,
  max(LISTED_BUILDING)LISTED_BUILDING,
  max(LOCAL_NATURE_RESERVE) LOCAL_NATURE_RESERVE,
  max(MAJOR_ROAD_JUNCTION) MAJOR_ROAD_JUNCTION,
  max(MAJOR_TUNNEL) MAJOR_TUNNEL,
  max(NATIONAL_NATURE_RESERVE) NATIONAL_NATURE_RESERVE,
  max(OIL_FUEL_DEPOT) OIL_FUEL_DEPOT,
  max(RAIL) RAIL,
  max(RAILWAY_LINE) RAILWAY_LINE ,
  max(RAILWAY_STATION) RAILWAY_STATION,
  max(RAMSAR) RAMSAR,
  max(RHPG) RHPG,
  max(SCHEDULED_MONUMENT) SCHEDULED_MONUMENT,
  max(SENSITIVE_BUILDING) SENSITIVE_BUILDING,
  max(SERVICE_RESERVOIR) SERVICE_RESERVOIR,
  max(SPECIAL_CONSERVATION_AREA) SPECIAL_CONSERVATION_AREA,
  max(SPECIAL_PROTECTED_AREA) SPECIAL_PROTECTED_AREA,
  max(SSSI) SSSI,
  max(STORAGE_RESERVOIR) STORAGE_RESERVOIR,
  max(SUBWAY) SUBWAY,
  max(UNDERGROUND_STATION) UNDERGROUND_STATION,
  max(WORLD_HERITAGE_SITE) WORLD_HERITAGE_SITE,
  max(ELECTRICITY) ELECTRICITY,
  max(GRAVEYARD) GRAVEYARD,
  max(RESIDENTIAL) RESIDENTIAL,
  max(GOVERNMENT) GOVERNMENT,
  max(FIRE_STATION) FIRE_STATION,
  max(EDUCATION) EDUCATION,
  max(COMMERCIAL) COMMERCIAL,
  max(AMBULANCE) AMBULANCE,
  max(POLICE) POLICE,
  max(HOSPITAL) HOSPITAL,
  max(AQUADUCT) AQUADUCT,
  max(BASEMENT) BASEMENT,
  max(MOTORWAY_AROAD) MOTORWAY_AROAD,
  max(STORAGE_RESERVOIR_STATUTORY) STORAGE_RESERVOIR_STATUTORY,
  max(REDROUTE) REDROUTE
FROM T_P_FLOOD_CONSEQUENCE_1D 
GROUP BY ICS_ASSET_ID
) FLD_1D             on core.ICS_ASSET_ID = FLD_1D.ICS_ASSET_ID
left join 
(
Select ICS_ASSET_ID, max(E_STORAGE_RESERVOIR_STATUTORY) E_STORAGE_RESERVOIR_STATUTORY, max(E_STORAGE_RESERVOIR) E_STORAGE_RESERVOIR, max(E_SERVICE_RESERVOIR) E_SERVICE_RESERVOIR from (
SELECT 
  ICS_ASSET_ID, 
  prox.ICS_BURST_ID,
  E_STORAGE_RESERVOIR_STATUTORY,
  E_STORAGE_RESERVOIR,
  E_SERVICE_RESERVOIR
FROM T_P_BURST_PROXIMITY prox
LEFT JOIN T_P_CRIT_TRUNK_MAIN_BURSTPTS fld_2d on prox.ICS_BURST_ID = fld_2d.ICS_BURST_ID
) group by ICS_ASSET_ID
)PROX on core.ICS_ASSET_ID = prox.ICS_ASSET_ID
LEFT JOIN VW_P_DMA_LOWEST_LEAK min_leak on core.DMA = min_leak.DMA
WHERE core.ASSET_FUNCTION_BIN = upper('distribution');
